influxdb:
  org: 'UPM'
  bucket: 'Gait/autogen'
  measurement: 'Gait'
  url: "https://apiivm78.etsii.upm.es:8086"
  token: 'Zx2jR8PD6h3YlS7HVsY5Han1SzF_iz7uk8n5z9BYRZ5q50lk8r1L18N-nFZiGCa57oowLgl8656pVpCig-GANg=='
  verify: false
  timeout: 900000

postgresql:
  host: "apiivm78.etsii.upm.es"
  user: "dpc"
  password: "UPM#2024"
  database: "sclerosis_dpc_2024"
  port: 5432

movement:
  # Umbral para el módulo de aceleración (is_effective_by_time)
  accel_threshold: 0.2
  # Umbral para el módulo de giroscopio (is_effective_by_time)
  gyro_threshold: 0.2
  # Threshold de potencia en la banda de frecuencia
  power_threshold: 0.5
  # Banda de frecuencia para Welch (Hz)
  freq_band_min: 0.4
  freq_band_max: 1.4
  # Segundos mínimos continuos sobre el umbral para considerar actividad
  min_continuous_seconds: 10
